### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by sabotage3d** [Amanieu/asyncplusplus#18]
Is Android supported currently?

**Comment by Amanieu** [comment]
I'm not personally familiar with Android, but as long as the system supports C++11 then the code should just work.

**Comment by DolceTriade** [comment]
Android NDK supports C++11.

**Comment by edkimmel** [comment]
I've been using this on Android for about two years now. It works out of the box if I remember correctly.  If you also decide to use it on iOS, you'll run into the problem of the thread_local keyword not being supported. I had to wrap the thread local pieces up in a struct that falls back to pthread calls.

**Comment by Amanieu** [comment]
@edkimmel TLS emulation for iOS was added in #15, so it should just work on iOS now. Feel free to send a PR if this is insufficient, since I don't have any iOS device myself to test this.

I will close this issue for now since Android works.
