### ISSUE TITLE
msvc 2017 build

### ISSUE THREAD

**Issue by Burning-Daylight** [Amanieu/asyncplusplus#19]
I tried building async++ with msvc 2017 and did not succeed, am I doing something wrong?

> C:\workspace\asyncplusplus\build>cmake .. -G "Visual Studio 15 Win64"
> -- The C compiler identification is MSVC 19.10.25019.0
> -- The CXX compiler identification is MSVC 19.10.25019.0
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for pthread.h
> -- Looking for pthread.h - not found
> -- Found Threads: TRUE
> -- Configuring done
> -- Generating done
> -- Build files have been written to: C:/workspace/asyncplusplus/build
> 
> C:\workspace\asyncplusplus\build>cmake --build . --target ALL_BUILD --config Release
> Microsoft (R) Build Engine version 15.1.1012.6693
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Build started 4/8/2017 3:03:05 PM.
> Project "C:\workspace\asyncplusplus\build\ALL_BUILD.vcxproj" on node 1 (default targets).
> Project "C:\workspace\asyncplusplus\build\ALL_BUILD.vcxproj" (1) is building "C:\workspace\asyncplusplus\build\ZERO_CHE
> CK.vcxproj" (2) on node 1 (default targets).
> PrepareForBuild:
>   Creating directory "x64\Release\ZERO_CHECK\".
>   Creating directory "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\".
> InitializeBuildStatus:
>   Creating "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
> CustomBuild:
>   Checking Build System
>   CMake does not need to re-run because C:/workspace/asyncplusplus/build/CMakeFiles/generate.stamp is up-to-date.
> FinalizeBuildStatus:
>   Deleting file "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
>   Touching "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
> Done Building Project "C:\workspace\asyncplusplus\build\ZERO_CHECK.vcxproj" (default targets).
> 
> Project "C:\workspace\asyncplusplus\build\ALL_BUILD.vcxproj" (1) is building "C:\workspace\asyncplusplus\build\Async++.
> vcxproj" (3) on node 1 (default targets).
> PrepareForBuild:
>   Creating directory "Async++.dir\Release\".
>   Creating directory "C:\workspace\asyncplusplus\build\Release\".
>   Creating directory "Async++.dir\Release\Async++.tlog\".
> InitializeBuildStatus:
>   Creating "Async++.dir\Release\Async++.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
> CustomBuild:
>   Building Custom Rule C:/workspace/asyncplusplus/CMakeLists.txt
>   CMake does not need to re-run because C:\workspace\asyncplusplus\build\CMakeFiles\generate.stamp is up-to-date.
> ClCompile:
>   C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x64\CL.exe /c /IC
>   :\workspace\asyncplusplus\include /nologo /W3 /WX- /diagnostics:classic /O2 /Ob2 /D WIN32 /D _WINDOWS /D NDEBUG /D "C
>   MAKE_INTDIR=\"Release\"" /D LIBASYNC_BUILD /D _WINDLL /D _MBCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScop
>   e /Zc:inline /GR- /Fo"Async++.dir\Release\\" /Fd"Async++.dir\Release\vc141.pdb" /Gd /TP /errorReport:queue C:\workspa
>   ce\asyncplusplus\src\scheduler.cpp C:\workspace\asyncplusplus\src\threadpool_scheduler.cpp
>   scheduler.cpp
> c:\workspace\asyncplusplus\include\async++/continuation_vector.h(135): error C2146: syntax error: missing ';' before id
> entifier 'tmp' [C:\workspace\asyncplusplus\build\Async++.vcxproj]
> c:\workspace\asyncplusplus\include\async++/continuation_vector.h(135): error C2275: 'async::detail::task_ptr': illegal
> use of this type as an expression [C:\workspace\asyncplusplus\build\Async++.vcxproj]
>   c:\workspace\asyncplusplus\include\async++/scheduler_fwd.h(58): note: see declaration of 'async::detail::task_ptr'
> c:\workspace\asyncplusplus\include\async++/continuation_vector.h(135): error C2065: 'i': undeclared identifier [C:\work
> space\asyncplusplus\build\Async++.vcxproj]
> c:\workspace\asyncplusplus\include\async++/continuation_vector.h(135): error C3861: 'tmp': identifier not found [C:\wor
> kspace\asyncplusplus\build\Async++.vcxproj]
>   threadpool_scheduler.cpp
> c:\workspace\asyncplusplus\include\async++/continuation_vector.h(135): error C2146: syntax error: missing ';' before id
> entifier 'tmp' [C:\workspace\asyncplusplus\build\Async++.vcxproj]
> c:\workspace\asyncplusplus\include\async++/continuation_vector.h(135): error C2275: 'async::detail::task_ptr': illegal
> use of this type as an expression [C:\workspace\asyncplusplus\build\Async++.vcxproj]
>   c:\workspace\asyncplusplus\include\async++/scheduler_fwd.h(58): note: see declaration of 'async::detail::task_ptr'
> c:\workspace\asyncplusplus\include\async++/continuation_vector.h(135): error C2065: 'i': undeclared identifier [C:\work
> space\asyncplusplus\build\Async++.vcxproj]
> c:\workspace\asyncplusplus\include\async++/continuation_vector.h(135): error C3861: 'tmp': identifier not found [C:\wor
> kspace\asyncplusplus\build\Async++.vcxproj]
>   Generating Code...
> Done Building Project "C:\workspace\asyncplusplus\build\Async++.vcxproj" (default targets) -- FAILED.
> 
> Done Building Project "C:\workspace\asyncplusplus\build\ALL_BUILD.vcxproj" (default targets) -- FAILED.
> 
> 
> Build FAILED.
> 
> "C:\workspace\asyncplusplus\build\ALL_BUILD.vcxproj" (default target) (1) ->
> "C:\workspace\asyncplusplus\build\Async++.vcxproj" (default target) (3) ->
> (ClCompile target) ->
>   c:\workspace\asyncplusplus\include\async++/continuation_vector.h(135): error C2146: syntax error: missing ';' before
> identifier 'tmp' [C:\workspace\asyncplusplus\build\Async++.vcxproj]
>   c:\workspace\asyncplusplus\include\async++/continuation_vector.h(135): error C2275: 'async::detail::task_ptr': illega
> l use of this type as an expression [C:\workspace\asyncplusplus\build\Async++.vcxproj]
>   c:\workspace\asyncplusplus\include\async++/continuation_vector.h(135): error C2065: 'i': undeclared identifier [C:\wo
> rkspace\asyncplusplus\build\Async++.vcxproj]
>   c:\workspace\asyncplusplus\include\async++/continuation_vector.h(135): error C3861: 'tmp': identifier not found [C:\w
> orkspace\asyncplusplus\build\Async++.vcxproj]
>   c:\workspace\asyncplusplus\include\async++/continuation_vector.h(135): error C2146: syntax error: missing ';' before
> identifier 'tmp' [C:\workspace\asyncplusplus\build\Async++.vcxproj]
>   c:\workspace\asyncplusplus\include\async++/continuation_vector.h(135): error C2275: 'async::detail::task_ptr': illega
> l use of this type as an expression [C:\workspace\asyncplusplus\build\Async++.vcxproj]
>   c:\workspace\asyncplusplus\include\async++/continuation_vector.h(135): error C2065: 'i': undeclared identifier [C:\wo
> rkspace\asyncplusplus\build\Async++.vcxproj]
>   c:\workspace\asyncplusplus\include\async++/continuation_vector.h(135): error C3861: 'tmp': identifier not found [C:\w
> orkspace\asyncplusplus\build\Async++.vcxproj]
> 
>     0 Warning(s)
>     8 Error(s)
> 
> Time Elapsed 00:00:04.54
>

**Comment by Amanieu** [comment]
Does changing line 135 of include/async++/continuation_vector.h from
```c++
task_ptr tmp(i);
```
to
```c++
(task_ptr(i));
```
help?

**Comment by Burning-Daylight** [comment]
Yes, thank you!
