### ISSUE TITLE
async::when_any crashes

### ISSUE THREAD

**Issue by sroycode** [Amanieu/asyncplusplus#20]
The following code crashes often with Clang 8.0 on MacOSX , what am I doing wrong ?

```
#include <iostream>
#include <array>
#include <async++.h>

int main ()
{
  std::array<async::task<char>,3> tasks {
    async::spawn([] {return 'A';}),
    async::spawn([] {return 'B';}),
    async::spawn([] {return 'C';}),
  };

  async::when_any(tasks.begin(),tasks.end()).then(
  [](async::when_any_result<std::vector<async::task<char>>> result) {
    std::cout << "Task " << result.index << " finished with value "
              << result.tasks[result.index].get() << std::endl;
  });
  return 0;
}
```

**Comment by Amanieu** [comment]
I believe the problem is that the `tasks` array goes out of scope while `when_any` still holds a reference to it.

**Comment by Amanieu** [comment]
Sorry, that was incorrect. It seems to work fine for me.

**Comment by Amanieu** [comment]
Can you provide a backtrace of the crash?

**Comment by sroycode** [comment]
Actually it is a fairly random thing, I did a workaround on line 269 of

https://github.com/sroycode/ribhu/blob/master/src/tools/OsmHandler.cc
