### ISSUE TITLE
Custom scheduler for Android and iOS

### ISSUE THREAD

**Issue by bilsou** [Amanieu/asyncplusplus#27]
Been trying to use asyncplusplus on iOS and Android. 
Works well so far when used only on the C++ side. But once one starts doing complex things (UI scheduling typically, completely different on iOS and Android), things get complicated.
I have seen the gtk_scheduler example. I was wondering how one could write a custom scheduler using libdispatch for iOS and ALooper for Android. 
Any hint/help would be much appreciated.

**Comment by Amanieu** [comment]
Unfortunately I am not familiar enough with either iOS or Android to help you here.

I had a quick look at ALooper, it seems to be mainly for waiting on file descriptors rather than scheduling tasks. For that you will want to use `event_task` rather than a custom scheduler.

**Comment by bilsou** [comment]
That's a bummer but fair enough, thank you for your answer.
I just found this https://github.com/mknejp/schedulers, cross platform scheduler for iOS/Android. 
Need to see how I could integrate it with asyncplusplus
