### ISSUE TITLE
Change the name of the async namespace

### ISSUE THREAD

**Issue by zerodefect** [Amanieu/asyncplusplus#30]
Firstly, this is a terrific project. It does just what it says on the tin.

The `async` namespace that is used in this project is far too generic in my opinion and could lead to some confusion or the potential for clashes.

Could I propose changing the namespace to something like `asyncpp` ?

**Comment by Amanieu** [comment]
I don't think it's worth the trouble of changing this unless you know of another library that also uses this namespace.

**Comment by zerodefect** [comment]
Ok. No, I don't know of another library with this namespace. My concern is that for someone new to C++ who is reading a large code base with the asyncplusplus project as a dependency, they might be inclined to believe that the async functionality is a feature provided by default by C++ itself.  Furthermore, it would also be nice if the name of the namespace married up with the name of the project a bit more.
