### ISSUE TITLE
exception matching is broken on macos due to -fno-rtti in asyncplusplus library

### ISSUE THREAD

**Issue by kikaxa** [Amanieu/asyncplusplus#32]
Greetings, 

When we do e.g.
```
        try { throw std::runtime_error("err"); }  
        catch (std::exception& e){ std::cout << e.what(); }
```
on macos/xcode and link with async++(static?) lib, the exception won't be matched.

For the explanation please see https://stackoverflow.com/questions/21737201/problems-throwing-and-catching-exceptions-on-os-x-with-fno-rtti

**Comment by Amanieu** [comment]
It should be fixed now.
