### ISSUE TITLE
error on centos 7

### ISSUE THREAD

**Issue by BotellaA** [Amanieu/asyncplusplus#36]
I tried to compile my project using async++ for the first time on Centos7 using gcc 4.8.2 and I got this error:
```
undefined reference to `void std::atomic_init<async::detail::compressed_ptr<3ul, true> >(std::atomic<async::detail::compressed_ptr<3ul, true> >*, async::detail::compressed_ptr<3ul, true>)'
```

Does it mean something to you? Thanks for your help

**Comment by Amanieu** [comment]
Basically gcc forgot to implement `atomic_init` when implementing C++11 support ([bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64658)). I believe this is fixed in gcc 4.9.

Alternatively you can replace the call to `atomic_init` with a relaxed store:
```c++
atomic_data.store(internal_data(nullptr, 0), std::memory_order_relaxed);
```

**Comment by BotellaA** [comment]
Thanks for the explanation. 

Where should I replace it? In an async++ fork?

**Comment by Amanieu** [comment]
I'll push a fix
