### ISSUE TITLE
wait on parallel_for results

### ISSUE THREAD

**Issue by psychoticbeef** [Amanieu/asyncplusplus#38]
Is it possible to wait on parallel_for results to then synchronously use all the results together?
Or how is this issue solvable with your API? I was hoping parallel_for would return tasks that I could .when_all() on, but it's void.

**Comment by Amanieu** [comment]
`parallel_for` will block until all operations are done. If you don't want to block on a `parallel_for`, you can wrap it in a task.

**Comment by psychoticbeef** [comment]
That's nice! Can I return results from the parallel_for loop?

**Comment by Amanieu** [comment]
You can create a `vector<T>` before the loop and store your results into it from within the loop lambda.

**Comment by psychoticbeef** [comment]
That'd need additional synchronization though, right?

**Comment by Amanieu** [comment]
As long as each loop iteration touches a separate vector element then no synchronization is needed. Make sure to resize your vector to the right size before calling `parallel_for`.

**Comment by psychoticbeef** [comment]
That satifies my use-case. Thank you! I like your library a lot. <3
