### ISSUE TITLE
task using unique_ptr

### ISSUE THREAD

**Issue by BotellaA** [Amanieu/asyncplusplus#45]
I have an issue with an example using unique_ptr.
```
auto value = std::make_unique< int >( 12 );
auto t1 = async::spawn( [&value] { std::cout << *value << std::endl; } );
async::when_all( t1 );
```
This code prints a random number instead of 12.
If I use `t1.wait()` instead of `when_all`, it works.

**Comment by Amanieu** [comment]
You need to wait on the task returned by `when_all`.

**Comment by BotellaA** [comment]
Thanks
