### ISSUE TITLE
How to catch an exception with when_all()?

### ISSUE THREAD

**Issue by BotellaA** [Amanieu/asyncplusplus#53]
I do not understand how to handle exceptions in the case of a `when_all()`.
Here is my simple example. 
```
        std::vector< async::task< void > > tasks;
        for( int t = 0; t < 10; t++ )
        {
            tasks.emplace_back( async::spawn( [] {
                throw std::runtime_error( "Some list error" );
            } ) );
        }
        async::when_all( tasks.begin(), tasks.end() ).get();
```
I understood that `get()` (instead of `wait()`) would return the exception but nothing happened.

Thanks for your help!

**Comment by Amanieu** [comment]
.get() returns a vector of tasks. You need to call .get on the inner tasks to get the exceptions out.

**Comment by BotellaA** [comment]
Thanks! I got it!
