### ISSUE TITLE
Please, create a new release based on the master branch

### ISSUE THREAD

**Issue by JanWilczek** [Amanieu/asyncplusplus#60]
A new release (version 1.2 or 1.1.1) would indicate that the most recent changes from `master` are incorporated which is important for package managers like vcpkg. In this way, vcpkg port of asyncplusplus could be easily updated.

vcpkg encourages creators of port update PRs to ask for new releases: https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md#follow-common-conventions-for-the-version-field

**Comment by Amanieu** [comment]
I've tagged a new release, however do note that I am no longer actively maintaining this library.

**Comment by JanWilczek** [comment]
Thank you @Amanieu !
